[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.2"

[features]
seeds = false
skip-lint = false

[programs.localnet]
ideapad_programs = "49KpHHeP9Hx2TBnHYLZvVYTpc1q2bt2NTvZdr4bMfFea"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/professormint/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
